/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type Host = {
  _id: string;
  _type: "host";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  role?: string;
  avatar?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Guest = {
  _id: string;
  _type: "guest";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  role?: string;
  avatar?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
};

export type GuestReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "guest";
};

export type HostReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "host";
};

export type Episode = {
  _id: string;
  _type: "episode";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  episodeNumber?: number;
  title?: string;
  slug?: Slug;
  guests?: Array<
    {
      _key: string;
    } & GuestReference
  >;
  hosts?: Array<
    {
      _key: string;
    } & HostReference
  >;
  publishedAt?: string;
  durationMinutes?: number;
  artwork?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  showNotes?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | SanityImageAssetReference
  | Host
  | SanityImageCrop
  | SanityImageHotspot
  | Guest
  | GuestReference
  | HostReference
  | Episode
  | Slug
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: ../virtually-built/src/api/episodes.ts
// Variable: EPISODES_PAGE_QUERY
// Query: *[_type == "episode" && defined(slug.current)] | order(publishedAt desc) [$start...$end] {    _id,    episodeNumber,    title,    slug,    guests[]->{      _id,      name,      role    },    publishedAt,    durationMinutes,    artwork {      asset,      alt,      hotspot,      crop    },    "showNotes": pt::text(showNotes)  }
export type EPISODES_PAGE_QUERY_RESULT = Array<{
  _id: string;
  episodeNumber: number | null;
  title: string | null;
  slug: Slug | null;
  guests: Array<{
    _id: string;
    name: string | null;
    role: string | null;
  }> | null;
  publishedAt: string | null;
  durationMinutes: number | null;
  artwork: {
    asset: SanityImageAssetReference | null;
    alt: string | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
  } | null;
  showNotes: string;
}>;

// Source: ../virtually-built/src/sanity/queries/episodes.ts
// Variable: EPISODE_QUERY
// Query: *[_type == "episode" && slug.current == $slug][0]{    _id,    episodeNumber,    title,    slug,    guests[]->{      _id,      name,      role,      avatar {        asset,        alt,        hotspot,        crop      }    },    publishedAt,    durationMinutes,    artwork {      asset,      alt,      hotspot,      crop    },    showNotes,    "showNotesExcerpt": pt::text(showNotes),    youtubeUrl,    transcript[]{      start,      speaker,      text    },    hosts[]->{      _id,      name,      role,      avatar {        asset,        alt,        hotspot,        crop      }    }  }
export type EPISODE_QUERY_RESULT = {
  _id: string;
  episodeNumber: number | null;
  title: string | null;
  slug: Slug | null;
  guests: Array<{
    _id: string;
    name: string | null;
    role: string | null;
    avatar: {
      asset: SanityImageAssetReference | null;
      alt: string | null;
      hotspot: SanityImageHotspot | null;
      crop: SanityImageCrop | null;
    } | null;
  }> | null;
  publishedAt: string | null;
  durationMinutes: number | null;
  artwork: {
    asset: SanityImageAssetReference | null;
    alt: string | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
  } | null;
  showNotes: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  showNotesExcerpt: string | null;
  youtubeUrl: string | null;
  transcript: Array<{
    start: number | null;
    speaker: string | null;
    text: string | null;
  }> | null;
  hosts: Array<{
    _id: string;
    name: string | null;
    role: string | null;
    avatar: {
      asset: SanityImageAssetReference | null;
      alt: string | null;
      hotspot: SanityImageHotspot | null;
      crop: SanityImageCrop | null;
    } | null;
  }> | null;
} | null;

// Source: ../virtually-built/src/sanity/queries/episodes.ts
// Variable: EPISODE_METADATA_QUERY
// Query: *[_type == "episode" && slug.current == $slug][0]{    title,    episodeNumber,    publishedAt,    durationMinutes,    youtubeUrl,    "showNotesExcerpt": pt::text(showNotes),    artwork {      asset,      alt,      hotspot,      crop    },    guests[]->{      name    }  }
export type EPISODE_METADATA_QUERY_RESULT = {
  title: string | null;
  episodeNumber: number | null;
  publishedAt: string | null;
  durationMinutes: number | null;
  youtubeUrl: string | null;
  showNotesExcerpt: string | null;
  artwork: {
    asset: SanityImageAssetReference | null;
    alt: string | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
  } | null;
  guests: Array<{
    name: string | null;
  }> | null;
} | null;

// Source: ../virtually-built/src/sanity/queries/episodes.ts
// Variable: RELATED_EPISODES_QUERY
// Query: *[_type == "episode" && slug.current != $slug && episodeNumber in $numbers] | order(episodeNumber desc) {    _id,    episodeNumber,    title,    slug,    guests[]->{      _id,      name,      role    },    publishedAt,    durationMinutes,    artwork {      asset,      alt,      hotspot,      crop    },    "showNotes": pt::text(showNotes)  }
export type RELATED_EPISODES_QUERY_RESULT = Array<{
  _id: string;
  episodeNumber: number | null;
  title: string | null;
  slug: Slug | null;
  guests: Array<{
    _id: string;
    name: string | null;
    role: string | null;
  }> | null;
  publishedAt: string | null;
  durationMinutes: number | null;
  artwork: {
    asset: SanityImageAssetReference | null;
    alt: string | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
  } | null;
  showNotes: string;
}>;

// Source: ../virtually-built/src/sanity/queries/episodes.ts
// Variable: LATEST_EPISODE_SLUG_QUERY
// Query: *[_type == "episode" && defined(slug.current)] | order(publishedAt desc)[0].slug.current
export type LATEST_EPISODE_SLUG_QUERY_RESULT = string | null;

// Source: ../virtually-built/src/sanity/queries/episodes.ts
// Variable: EPISODES_COUNT_QUERY
// Query: count(*[_type == "episode" && defined(slug.current)])
export type EPISODES_COUNT_QUERY_RESULT = number;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '*[_type == "episode" && defined(slug.current)] | order(publishedAt desc) [$start...$end] {\n    _id,\n    episodeNumber,\n    title,\n    slug,\n    guests[]->{\n      _id,\n      name,\n      role\n    },\n    publishedAt,\n    durationMinutes,\n    artwork {\n      asset,\n      alt,\n      hotspot,\n      crop\n    },\n    "showNotes": pt::text(showNotes)\n  }': EPISODES_PAGE_QUERY_RESULT;
    '*[_type == "episode" && slug.current == $slug][0]{\n    _id,\n    episodeNumber,\n    title,\n    slug,\n    guests[]->{\n      _id,\n      name,\n      role,\n      avatar {\n        asset,\n        alt,\n        hotspot,\n        crop\n      }\n    },\n    publishedAt,\n    durationMinutes,\n    artwork {\n      asset,\n      alt,\n      hotspot,\n      crop\n    },\n    showNotes,\n    "showNotesExcerpt": pt::text(showNotes),\n    youtubeUrl,\n    transcript[]{\n      start,\n      speaker,\n      text\n    },\n    hosts[]->{\n      _id,\n      name,\n      role,\n      avatar {\n        asset,\n        alt,\n        hotspot,\n        crop\n      }\n    }\n  }': EPISODE_QUERY_RESULT;
    '*[_type == "episode" && slug.current == $slug][0]{\n    title,\n    episodeNumber,\n    publishedAt,\n    durationMinutes,\n    youtubeUrl,\n    "showNotesExcerpt": pt::text(showNotes),\n    artwork {\n      asset,\n      alt,\n      hotspot,\n      crop\n    },\n    guests[]->{\n      name\n    }\n  }': EPISODE_METADATA_QUERY_RESULT;
    '*[_type == "episode" && slug.current != $slug && episodeNumber in $numbers] | order(episodeNumber desc) {\n    _id,\n    episodeNumber,\n    title,\n    slug,\n    guests[]->{\n      _id,\n      name,\n      role\n    },\n    publishedAt,\n    durationMinutes,\n    artwork {\n      asset,\n      alt,\n      hotspot,\n      crop\n    },\n    "showNotes": pt::text(showNotes)\n  }': RELATED_EPISODES_QUERY_RESULT;
    '*[_type == "episode" && defined(slug.current)] | order(publishedAt desc)[0].slug.current': LATEST_EPISODE_SLUG_QUERY_RESULT;
    'count(*[_type == "episode" && defined(slug.current)])': EPISODES_COUNT_QUERY_RESULT;
  }
}
